- name: Install stow
  become: true
  community.general.pacman:
    name: stow
  tags:
    - install
    - dotfiles

- name: Clone dotfiles
  ansible.builtin.git:
    repo: https://github.com/jp-belanger/dotfiles.git
    dest: "{{ dotfiles_dir }}"
    recursive: true
    update: true
    version: master
  become: true
  become_user: "{{ dev_user }}"
  tags:
    - install
    - dotfiles

- name: Restow dotfiles
  ansible.builtin.command: "stow -R -t {{ dev_home }} -d {{ dotfiles_dir }} {{ item }}"
  become: true
  become_user: "{{ dev_user }}"
  loop:
    - zsh
    - tmux
    - nvim
    - ipython
  changed_when: false
  tags:
    - install
    - dotfiles
