- name: Remove system default dotfiles on install
  file:
    path: "{{ user_home }}/{{ item }}"
    state: absent
  loop:
    - .zshrc
  tags:
    - install
    - dotfiles

- name: Install stow
  become: true
  pacman: 
    name: stow
  tags:
    - install
    - dotfiles

- name: Cloning dotfiles
  git:
    repo: https://github.com/jp-belanger/dotfiles.git
    dest: "{{ dotfiles_dir }}"
    recursive: true
    update: true
    version: master
  tags:
    - install
    - dotfiles

- name: Restow dotfiles
  command: "stow -R -t {{ user_home }} -d {{ dotfiles_dir }} {{ item }}"
  loop:
    - zsh
    - tmux
    - nvim
    - ipython
  changed_when: false
  tags:
    - install
    - dotfiles
