- name: Install rustup
  become: true
  community.general.pacman:
    name: rustup
  tags:
    - install
    - rust

- name: Install rust stable version
  ansible.builtin.command: rustup toolchain install stable
  become: true
  become_user: "{{ dev_user }}"
  changed_when: false
  tags:
    - install
    - rust

- name: Install rust nightly version
  ansible.builtin.command: rustup toolchain install nightly
  become: true
  become_user: "{{ dev_user }}"
  changed_when: false
  tags:
    - install
    - rust

- name: Setup default rust version to stable
  ansible.builtin.command: rustup default stable
  become: true
  become_user: "{{ dev_user }}"
  changed_when: false
  tags:
    - install
    - rust
