- name: Authorize personal SSH key
  ansible.posix.authorized_key:
    user: "{{ dev_user }}"
    state: present
    key: "{{ personal_authorized_key }}"
  become: true
  tags:
    - install
    - ssh
