- name: Install tailscale
  become: true
  pacman:
    name:
      - tailscale
  tags:
    - install
    - tailscale

- name: Enable and start tailscaled
  become: true
  systemd:
    name: tailscaled
    enabled: true
    state: started
  tags:
    - install
    - tailscale
