- name: Setup dev tools
  become: true
  community.general.pacman:
    name:
      - tmux
      - tldr
      - ripgrep
      - fd
      - github-cli
      - jq
      - bat
      - btop
      - eza
      - wget
      - curl
      - tree
      - rsync
      - unzip
      - zip
      - man-db
      - less
      - man-pages
      - luarocks
      - docker
      - docker-compose
      - fastfetch
  tags:
    - install
    - tools
