- name: Install zsh
  become: true
  community.general.pacman:
    name: zsh
  tags:
    - install
    - zsh

- name: Change default shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ dev_user }}"
    shell: /usr/bin/zsh
  tags:
    - install
    - zsh
